# clk_in
set_property PACKAGE_PIN E3 [get_ports clk_in]
set_property IOSTANDARD LVCMOS33 [get_ports clk_in]

# interrupt
set_property PACKAGE_PIN T16 [get_ports interrupt_signs_in[2]]
set_property IOSTANDARD LVCMOS33 [get_ports interrupt_signs_in[2]]
set_property PACKAGE_PIN E16 [get_ports interrupt_signs_in[1]]
set_property IOSTANDARD LVCMOS33 [get_ports interrupt_signs_in[1]]
set_property PACKAGE_PIN R10 [get_ports interrupt_signs_in[0]]
set_property IOSTANDARD LVCMOS33 [get_ports interrupt_signs_in[0]]

# display_src
set_property PACKAGE_PIN U9 [get_ports display_src[0]]
set_property IOSTANDARD LVCMOS33 [get_ports display_src[0]]
set_property PACKAGE_PIN U8 [get_ports display_src[1]]
set_property IOSTANDARD LVCMOS33 [get_ports display_src[1]]
set_property PACKAGE_PIN R7 [get_ports display_src[2]]
set_property IOSTANDARD LVCMOS33 [get_ports display_src[2]]

# display_seg
set_property PACKAGE_PIN L3 [get_ports display_seg[0]]
set_property IOSTANDARD LVCMOS33 [get_ports display_seg[0]]
set_property PACKAGE_PIN N1 [get_ports display_seg[1]]
set_property IOSTANDARD LVCMOS33 [get_ports display_seg[1]]
set_property PACKAGE_PIN L5 [get_ports display_seg[2]]
set_property IOSTANDARD LVCMOS33 [get_ports display_seg[2]]
set_property PACKAGE_PIN L4 [get_ports display_seg[3]]
set_property IOSTANDARD LVCMOS33 [get_ports display_seg[3]]
set_property PACKAGE_PIN K3 [get_ports display_seg[4]]
set_property IOSTANDARD LVCMOS33 [get_ports display_seg[4]]
set_property PACKAGE_PIN M2 [get_ports display_seg[5]]
set_property IOSTANDARD LVCMOS33 [get_ports display_seg[5]]
set_property PACKAGE_PIN L6 [get_ports display_seg[6]]
set_property IOSTANDARD LVCMOS33 [get_ports display_seg[6]]
set_property PACKAGE_PIN M4 [get_ports display_seg[7]]
set_property IOSTANDARD LVCMOS33 [get_ports display_seg[7]]

# display_ctrl
set_property PACKAGE_PIN N6 [get_ports display_ctrl[0]]
set_property IOSTANDARD LVCMOS33 [get_ports display_ctrl[0]]
set_property PACKAGE_PIN M6 [get_ports display_ctrl[1]]
set_property IOSTANDARD LVCMOS33 [get_ports display_ctrl[1]]
set_property PACKAGE_PIN M3 [get_ports display_ctrl[2]]
set_property IOSTANDARD LVCMOS33 [get_ports display_ctrl[2]]
set_property PACKAGE_PIN N5 [get_ports display_ctrl[3]]
set_property IOSTANDARD LVCMOS33 [get_ports display_ctrl[3]]
set_property PACKAGE_PIN N2 [get_ports display_ctrl[4]]
set_property IOSTANDARD LVCMOS33 [get_ports display_ctrl[4]]
set_property PACKAGE_PIN N4 [get_ports display_ctrl[5]]
set_property IOSTANDARD LVCMOS33 [get_ports display_ctrl[5]]
set_property PACKAGE_PIN L1 [get_ports display_ctrl[6]]
set_property IOSTANDARD LVCMOS33 [get_ports display_ctrl[6]]
set_property PACKAGE_PIN M1 [get_ports display_ctrl[7]]
set_property IOSTANDARD LVCMOS33 [get_ports display_ctrl[7]]
